version: "3.3"

networks:
  evolution-net:
    name: evolution-net
    driver: bridge

services:
  nest-documents:
    build: .
    restart: on-failure
    container_name: nest-documents
    networks:
      - evolution-net
    image: nest-documents
    command: npm run start
    ports:
      - "3000:3000"